### PR TITLE
Fixed the generation of the "prev" option in JSON generator

### LINKED ISSUE #74: The fjson file should keep the "parents" option
Sphinx describes the `parents` option as:

```
parents, prev and next:
    Information about related chapters in the TOC tree. Each relation is a
    dictionary with the keys link (HREF for the relation) and title (title
    of the related document, as HTML). parents is a list of relations,
    while prev and next are a single relation.
```

Source: https://www.sphinx-doc.org/en/1.0/builders.html#serialization-builder-details

-----

An example in practice:

This RST file from the Symfony Docs ->
https://github.com/symfony/symfony-docs/blob/5.x/contributing/code/bugs.rst

Is included in this `index.rst` from the section it belongs to:
https://github.com/symfony/symfony-docs/blob/5.x/contributing/code/index.rst

Which in turn is included in this `index.rst` from the main section:
https://github.com/symfony/symfony-docs/blob/5.x/contributing/index.rst

When the `*.fjson` is generated, it contains the following `parents`:

```json
"parents": [
    {"link": "../index.html", "title": "Contributing"},
    {"link": "index.html", "title": "Contributing Code"}
]
```

This is used in some parts of symfony.com to generate the breadcrumbs, so we'd need to re-add this option. I don't know if it's very complicated to do so or not 😐

### LINKED ISSUE #75: The `prev` option in fjson files is always null
We were checking the generated `fjson` files and we found that `next` option works perfectly, but the related `prev` option is always `null`.

Example:

This file -> https://github.com/EasyCorp/EasyAdminBundle/blob/master/doc/index.rst

The `crud` item is after `dashboards` and before `design`, but in the fjson file we get this:

```json
    "next": {
        "title": "Design",
        "link": "design.html"
    },
    "prev": null,
```

Now, if you look at `design`, you should find `crud` as `prev`. Instead, you find this:

```json
    "next": {
        "title": "Fields",
        "link": "fields.html"
    },
    "prev": null,
```

Given that `next` is working perfectly, maybe this has a non-complex fix? Thanks!

### PR DESCRIPTION
**Pull request by javiereguiluz**
Fixes #75.

Fixes #74 

This fixed the problem for me ... but I don't know the internals well enough, so I don't know the full implications of this change. Thanks for reviewing this proposal!

**UPDATE FROM @weaverryan**

I hijacked this PR and completely revamped the next/prev/parents functionality. It's now based exactly on how Sphinx works and it "should" be working identically.

### CODE REVIEW

**Comment by weaverryan** [comment]
Thanks for this Javier! I'm currently looking deeper into the toc tree handling in general - it was (I admit) once place I didn't give any serious attention to until now.

**Review by nikophil — APPROVED** [review]
I can't see any case where we having `'index' === $parentFile` would result into "prev" being null...

**Comment by weaverryan** [comment]
I've hijacked tis PR! Description updated :)

File: src/DocBuilder.php [hunk 1]
```diff
@@ -25,7 +25,10 @@ public function build(BuildConfig $config): BuildResult
         $builder = new Builder(KernelFactory::createKernel($config));
         $builder->build($config->getContentDir(), $config->getOutputDir());
 
-        $buildResult = new BuildResult($builder->getErrorManager()->getErrors());
+        $buildResult = new BuildResult(
```
Comment (javiereguiluz) [inline src/DocBuilder.php:28]: We don't use the `BuildResult` class directly anywhere, so if you want to simply pass the `$builder` as argument, it's OK to do so:

```php
$buildResult = new BuildResult($builder);
```

File: src/Generator/JsonGenerator.php [hunk 2]
```diff
@@ -37,28 +37,49 @@ public function __construct(Metas $metas, BuildConfig $buildConfig)
...
             $data = [
                 'title' => $metaEntry->getTitle(),
+                'parents' => $this->determineParents($parserFilename, $tocTreeHierarchy) ?: [],
                 'current_page_name' => $parserFilename,
                 'toc' => $this->generateToc($metaEntry, current($metaEntry->getTitles())[1]),
-                'next' => $this->guessNext($parserFilename),
-                'prev' => $this->guessPrev($parserFilename),
+                'next' => $next,
+                'prev' => $prev,
                 'rellinks' => [
```
Comment (javiereguiluz) [inline src/Generator/JsonGenerator.php:79]: This is the official Sphinx explanation of `rellinks`: https://www.sphinx-doc.org/en/master/templating.html#rellinks

I'd leave this as it is because I think we don't use this option anywhere.

File: tests/fixtures/source/json/crud.rst [hunk 3]
```diff
@@ -0,0 +1,7 @@
+CRUD
+====
+
+CRUD stands for: "create, read, update, delete".
+
+Or it might be: "Crazy runner's utter delight" (which would
```
Comment (javiereguiluz) [inline tests/fixtures/source/json/crud.rst:6]: 😂

File: tests/fixtures/source/json/fields.rst [hunk 4]
```diff
@@ -0,0 +1,5 @@
+Fields
+======
+
+I love fields: big open prairies, grass fields, corn fields... reall,
```
Comment (javiereguiluz) [inline tests/fixtures/source/json/fields.rst:4]: `reall` -> `really` ?

**Review by javiereguiluz — COMMENTED** [review]
Ryan, thanks for this great contribution!

I love how you fixed everything, while simplifying and improving everything at the same time. Stellar work! 🙇‍♂️

File: src/BuildResult.php [hunk 5]
```diff
@@ -40,4 +44,36 @@ public function getErrors(): array
     {
         return $this->errors;
     }
+
+    public function getMetas(): Metas
```
Comment (fabpot) [inline src/BuildResult.php:48]: Not directly related to this PR, but I suppose that `getMetadata()` would be more correct (which should also be modified in the builder).

File: src/BuildResult.php [hunk 6]
```diff
@@ -40,4 +44,36 @@ public function getErrors(): array
...
+    {
+        return $this->builder->getMetas();
+    }
+
+    /**
+     * Returns the "master document": the first file whose toctree is parsed.
+     *
+     * Unless customized, this is "index" (i.e. file index.rst).
+     *
+     * @return string
```
Comment (fabpot) [inline src/BuildResult.php:58]: Could removed as the PHP signature has the same. Not sure what's the policy in this repo though.

File: src/BuildResult.php [hunk 7]
```diff
@@ -40,4 +44,36 @@ public function getErrors(): array
...
+     */
+    public function getMasterDocumentFilename(): string
+    {
+        return $this->builder->getIndexName();
+    }
+
+    /**
+     * Returns the JSON data generated for each file, keyed by the source filename.
+     *
+     * @return array[]
```
Comment (fabpot) [inline src/BuildResult.php:68]: If description is good, this type hint looks wrong.

File: src/Generator/JsonGenerator.php (hunk 2 above)
Comment (fabpot) [reply src/Generator/JsonGenerator.php:79]: As we already have changed the format of the file anyway, we could remove rellinks support as we don't use it anywhere AFAIK.

**Review by fabpot — COMMENTED** [review]
Some random comments

File: src/Generator/JsonGenerator.php (hunk 2 above)
Comment (weaverryan) [reply src/Generator/JsonGenerator.php:79]: I have removed it. If there is other information that would be useful, let me know and we an add it :)

File: src/BuildResult.php (hunk 6 above)
Comment (weaverryan) [reply src/BuildResult.php:58]: Yes, thank you - my editor added that, it was not my intention.
